name: py35
channels:
- scitools
dependencies:
- python=3.5
- basemap
- cartopy
- gdal
- iris
- ipywidgets
- jupyter
- basemap
- gdal
- iris
- matplotlib
- numpy
- scipy
- pip:
  - git+https://github.com/dennissergeev/pyveccalc.git
  - git+https://github.com/dennissergeev/umtools.git
